# Generated by Django 5.1.1 on 2024-09-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=100)),
                ('destination_iata', models.CharField(max_length=10)),
                ('origin', models.CharField(max_length=100)),
                ('origin_iata', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('departure', models.DateField()),
                ('arrival', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'record',
            },
        ),
    ]
