# Generated by Django 5.1.1 on 2024-09-13 08:01


import threading
import math
from datetime import datetime, timedelta
from django.db import migrations, connection


def update_created_at(apps, schema_editor):
    two_days_ago = datetime.now() - timedelta(days=2)

    with connection.cursor() as cursor:
        cursor.execute("SELECT COUNT(*) FROM record")
        total_records = cursor.fetchone()[0]

    batch_size = 100000  
    total_batches = math.ceil(total_records / batch_size)

    def update_batch(start, end):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE record
                SET created_at = %s
                WHERE id >= %s AND id < %s
                """,
                [two_days_ago, start, end]
            )

    threads = []
    for i in range(total_batches):
        start_id = i * batch_size
        end_id = (i + 1) * batch_size
        t = threading.Thread(target=update_batch, args=(start_id, end_id))
        threads.append(t)
        t.start()


    for t in threads:
        t.join()


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_created_at'),  
    ]

    operations = [
        migrations.RunPython(update_created_at),
    ]
